### ISSUE TITLE
update to 2.4

### ISSUE THREAD

**Issue by flop25** [Ajtak/Cool-Piwigo-Template#1]
I've seen you are using the 2.3.8 version ; the last stable is 2.3.11
Since the 2.4 is in the RC stage, we should work on that branch

**Comment by Ajtak** [comment]
I will update to AdminLTE 2.4 on today evening. (CEST timezone).

**Comment by flop25** [comment]
Thx I was currently looking into it on my own

**Comment by Ajtak** [comment]
I'm upgrade template to AdminLTE 2.4RC and should be compatible.
